import { CarStockItem } from "./car-stock-types";

export const newCarStock: CarStockItem[] = [
  {
    id: "border-stock-zeekr-9x-max-2025-1",
    brand: "ZEEKR",
    model: "9X Max, 2025",
    fullModel: "ZEEKR 9X Max, 2025",
    year: 2025,
    price: "465 900",
    exteriorColor: "Чёрный «Полярная ночь»",
    interiorColor: "Янтарно-коричневый",
    colorCategory: "Black",
    configuration: "22-дюймовые кованые диски Starshine, 4-поршневые суппорты, 55 кВт·ч, матово-серебристый хром-пакет, Qianli Haohan H9, поворотные сиденья 2-го ряда, один 16-дюймовый центральный экран",
    location: "Хоргос",
    exwPrice: "$75 600",
    notes: "",
    battery: "",
    wheels: "",
    packages: "",
    image: "/images/cars/zeekr-9x-max-2025-black.jpg",
    category: "border-stock",
  },
  {
    id: "border-stock-zeekr-9x-hyper-2026-2",
    brand: "ZEEKR",
    model: "9X Hyper, 2026",
    fullModel: "ZEEKR 9X Hyper, 2026",
    year: 2026,
    price: "559 900",
    exteriorColor: "Чёрный «Полярная ночь»",
    interiorColor: "Лунно-синий",
    colorCategory: "Black",
    configuration: "22-дюймовые зеркальные кованые диски, 6-поршневые суппорты, 6 мест, подножки, батарея 70 кВт·ч, чёрный экстерьер-пакет, активный стабилизатор 48V, поворотные сиденья 2-го ряда, двойной центральный экран, умный электрофаркоп, H9",
    location: "Под заказ",
    exwPrice: "642000 ¥",
    notes: "",
    battery: "",
    wheels: "",
    packages: "",
    image: "/images/cars/zeekr-9x-hyper-2026-black.jpg",
    category: "border-stock",
  },
  {
    id: "border-stock-zeekr-9x-hyper-2026-3",
    brand: "ZEEKR",
    model: "9X Hyper, 2026",
    fullModel: "ZEEKR 9X Hyper, 2026",
    year: 2026,
    price: "559 900",
    exteriorColor: "Чёрный «Полярная ночь»",
    interiorColor: "Янтарно-коричневый",
    colorCategory: "Black",
    configuration: "22-дюймовые зеркальные кованые диски, 6-поршневые суппорты, 6 мест, подножки, батарея 70 кВт·ч, чёрный экстерьер-пакет, активный стабилизатор 48V, поворотные сиденья 2-го ряда, двойной центральный экран, умный электрофаркоп, H9",
    location: "Под заказ",
    exwPrice: "642000 ¥",
    notes: "",
    battery: "",
    wheels: "",
    packages: "",
    image: "/images/cars/zeekr-9x-hyper-2026-black.jpg",
    category: "border-stock",
  },
  {
    id: "border-stock-zeekr-9x-black-edition-4",
    brand: "ZEEKR",
    model: "9X Black Edition",
    fullModel: "ZEEKR 9X Black Edition",
    year: 2026,
    price: "599 900",
    exteriorColor: "Чёрный «Полярная ночь»",
    interiorColor: "Золотистый «Сияющая ночь»",
    colorCategory: "Black",
    configuration: "22-дюймовые чёрные кованые диски, 6-поршневые оранжевые суппорты, 6 мест, подножки, батарея 70 кВт·ч, Black Package, активный стабилизатор 48V, поворотные сиденья 2-го ряда, двойной центральный экран, умный электрофаркоп, H9",
    location: "Под заказ",
    exwPrice: "98000 $",
    notes: "",
    battery: "",
    wheels: "",
    packages: "",
    image: "/images/cars/zeekr-9x-black-edition-black.jpg",
    category: "border-stock",
  },
  {
    id: "border-stock-zeekr-009-guanghui-5",
    brand: "ZEEKR",
    model: "009 Guanghui",
    fullModel: "ZEEKR 009 Guanghui",
    year: 2025,
    price: "798 000",
    exteriorColor: "Чёрный «Полярная ночь»",
    interiorColor: "Снежно-белый",
    colorCategory: "Black",
    configuration: "Qianli Haohan H7",
    location: "Хоргос",
    exwPrice: "$105 000",
    notes: "Бронь",
    battery: "",
    wheels: "",
    packages: "",
    image: "/images/cars/zeekr-009-guanghui-black.jpg",
    category: "border-stock",
  },
  {
    id: "border-stock-byd-7-190-km-4wd-ultra-2025-6",
    brand: "BYD",
    model: "7 190 KM 4WD Ultra, 2025",
    fullModel: "BYD LEOPARD 7 190 KM 4WD Ultra, 2025",
    year: 2025,
    price: "219 800",
    exteriorColor: "Морозно-серый",
    interiorColor: "Облачно-оранжевый",
    colorCategory: "Gray",
    configuration: "",
    location: "Хоргос",
    exwPrice: "$31 400",
    notes: "",
    battery: "",
    wheels: "",
    packages: "",
    image: "/images/cars/BYD_7_190_KM_4WD_Ultra_2025_Gray.jpg",
    category: "border-stock",
  },
  {
    id: "border-stock-byd-7-190-km-4wd-ultra-2025-7",
    brand: "BYD",
    model: "7 190 KM 4WD Ultra, 2025",
    fullModel: "BYD LEOPARD 7 190 KM 4WD Ultra, 2025",
    year: 2025,
    price: "219 800",
    exteriorColor: "Обсидианово-чёрный",
    interiorColor: "Снежно-серый",
    colorCategory: "Black",
    configuration: "",
    location: "Хоргос",
    exwPrice: "$31 000",
    notes: "",
    battery: "",
    wheels: "",
    packages: "",
    image: "/images/cars/BYD_7_190_KM_4WD_Ultra_2025_Black.jpg",
    category: "border-stock",
  },
  {
    id: "border-stock-byd-7-190-km-4wd-ultra-2025-8",
    brand: "BYD",
    model: "7 190 KM 4WD Ultra, 2025",
    fullModel: "BYD LEOPARD 7 190 KM 4WD Ultra, 2025",
    year: 2025,
    price: "219 800",
    exteriorColor: "Горный зелёный",
    interiorColor: "Снежно-серый",
    colorCategory: "Green",
    configuration: "",
    location: "Хоргос",
    exwPrice: "$31 000",
    notes: "",
    battery: "",
    wheels: "",
    packages: "",
    image: "/images/cars/BYD_7_190_KM_4WD_Ultra_2025_Green.png",
    category: "border-stock",
  },
  {
    id: "border-stock-byd-7-190-km-4wd-ultra-2025-9",
    brand: "BYD",
    model: "7 190 KM 4WD Ultra, 2025",
    fullModel: "BYD LEOPARD 7 190 KM 4WD Ultra, 2025",
    year: 2025,
    price: "219 800",
    exteriorColor: "Горный зелёный",
    interiorColor: "Снежно-серый",
    colorCategory: "Green",
    configuration: "",
    location: "Наньша",
    exwPrice: "$31 000",
    notes: "",
    battery: "",
    wheels: "",
    packages: "",
    image: "/images/cars/BYD_7_190_KM_4WD_Ultra_2025_Green.png",
    category: "border-stock",
  },
  {
    id: "border-stock-byd-7-190-km-4wd-ultra-2025-10",
    brand: "BYD",
    model: "7 190 KM 4WD Ultra, 2025",
    fullModel: "BYD LEOPARD 7 190 KM 4WD Ultra, 2025",
    year: 2025,
    price: "219 800",
    exteriorColor: "Обсидианово-чёрный",
    interiorColor: "Снежно-серый",
    colorCategory: "Black",
    configuration: "",
    location: "Наньша",
    exwPrice: "$31 000",
    notes: "",
    battery: "",
    wheels: "",
    packages: "",
    image: "/images/cars/BYD_7_190_KM_4WD_Ultra_2025_Black.jpg",
    category: "border-stock",
  },
  {
    id: "border-stock-toyota-camry-20-hg-hybrid-premium-2024-11",
    brand: "Toyota",
    model: "Camry 2.0 HG Hybrid Premium, 2024",
    fullModel: "Toyota Camry 2.0 HG Hybrid Premium, 2024",
    year: 2024,
    price: "199 800",
    exteriorColor: "Кибер-серый",
    interiorColor: "Звёздно-чёрный",
    colorCategory: "Gray",
    configuration: "",
    location: "Хоргос",
    exwPrice: "$21 200",
    notes: "",
    battery: "",
    wheels: "",
    packages: "",
    image: "/images/cars/toyota-camry-20-hg-hybrid-premium-2024-gray.jpg",
    category: "border-stock",
  },
  {
    id: "border-stock-toyota-camry-20-hg-hybrid-premium-2024-12",
    brand: "Toyota",
    model: "Camry 2.0 HG Hybrid Premium, 2024",
    fullModel: "Toyota Camry 2.0 HG Hybrid Premium, 2024",
    year: 2024,
    price: "199 800",
    exteriorColor: "Чёрный «Звёздный кристалл»",
    interiorColor: "Звёздно-чёрный",
    colorCategory: "Black",
    configuration: "",
    location: "Хоргос",
    exwPrice: "$21 200",
    notes: "",
    battery: "",
    wheels: "",
    packages: "",
    image: "/images/cars/toyota-camry-20-hg-hybrid-premium-2024-black.jpg",
    category: "border-stock",
  },
  {
    id: "border-stock-toyota-camry-20-g-premium-2024-13",
    brand: "Toyota",
    model: "Camry 2.0 G Premium, 2024",
    fullModel: "Toyota Camry 2.0 G Premium, 2024",
    year: 2024,
    price: "191 800",
    exteriorColor: "Чёрный «Звёздный кристалл»",
    interiorColor: "Звёздно-чёрный",
    colorCategory: "Black",
    configuration: "",
    location: "Хоргос",
    exwPrice: "$20 100",
    notes: "",
    battery: "",
    wheels: "",
    packages: "",
    image: "/images/cars/toyota-camry-20-g-premium-2024-black.jpg",
    category: "border-stock",
  },
  {
    id: "zeekr-8x-ningbo-zeekr-max-14",
    brand: "ZEEKR",
    model: "8X Max",
    fullModel: "ZEEKR 8X Max",
    year: 2026,
    price: "",
    exteriorColor: "Чёрный",
    interiorColor: "Белый И Чёрный",
    colorCategory: "Black",
    configuration: "",
    location: "Нинбо",
    exwPrice: "Матовый: $62 711; Ночной: $65 333",
    notes: "",
    battery: "55kWh",
    wheels: "21-Дюймовые Двухтонные Колёсные Диски С Тормозными Суппортами Brembo На Четыре Поршня（shuangyao)",
    packages: "Электроподножки, 16\" Одиночный Центральный Экран, Qianli Haohan H7",
    image: "/images/cars/zeekr-8x-max-black.jpg",
    category: "zeekr-8x-ningbo",
  },
  {
    id: "zeekr-8x-ningbo-zeekr-max-15",
    brand: "ZEEKR",
    model: "8X Max",
    fullModel: "ZEEKR 8X Max",
    year: 2026,
    price: "",
    exteriorColor: "Чёрный",
    interiorColor: "Коричневый И Чёрный",
    colorCategory: "Black",
    configuration: "",
    location: "Нинбо",
    exwPrice: "Матовый: $62 711; Ночной: $65 333",
    notes: "",
    battery: "55kWh",
    wheels: "21-Дюймовые Двухтонные Колёсные Диски С Тормозными Суппортами Brembo На Четыре Поршня（shuangyao)",
    packages: "Электроподножки, 16\" Одиночный Центральный Экран, Qianli Haohan H7",
    image: "/images/cars/zeekr-8x-max-black.jpg",
    category: "zeekr-8x-ningbo",
  },
  {
    id: "zeekr-8x-ningbo-zeekr-ultra-16",
    brand: "ZEEKR",
    model: "8X Ultra+",
    fullModel: "ZEEKR 8X Ultra+",
    year: 2026,
    price: "",
    exteriorColor: "Чёрный",
    interiorColor: "Белый И Чёрный",
    colorCategory: "Black",
    configuration: "",
    location: "Нинбо",
    exwPrice: "Матовый: $70 881; Ночной: $72 193",
    notes: "",
    battery: "70kWh",
    wheels: "22-Дюймовые Сияющие Колёсные Диски С Четырехпоршневыми Тормозными Суппортами Brembo（huiyao)",
    packages: "Qianli Haohan H7, Электроподножки, Пакет Потолочных Экранов Задних Сидений, Аудио Naim Premium, Двойной центральный экран",
    image: "/images/cars/zeekr-8x-ultra-black.jpg",
    category: "zeekr-8x-ningbo",
  },
  {
    id: "zeekr-8x-ningbo-zeekr-ultra-17",
    brand: "ZEEKR",
    model: "8X Ultra+",
    fullModel: "ZEEKR 8X Ultra+",
    year: 2026,
    price: "",
    exteriorColor: "Чёрный",
    interiorColor: "Чистый Чёрный",
    colorCategory: "Black",
    configuration: "",
    location: "Нинбо",
    exwPrice: "Матовый: $70 881; Ночной: $72 193",
    notes: "",
    battery: "70kWh",
    wheels: "22-Дюймовые Сияющие Колёсные Диски С Четырехпоршневыми Тормозными Суппортами Brembo（huiyao)",
    packages: "Qianli Haohan H7, Электроподножки, Пакет Потолочных Экранов Задних Сидений, Аудио Naim Premium, Двойной центральный экран",
    image: "/images/cars/zeekr-8x-ultra-black.jpg",
    category: "zeekr-8x-ningbo",
  },
  {
    id: "zeekr-8x-ningbo-zeekr-ultra-18",
    brand: "ZEEKR",
    model: "8X Ultra+",
    fullModel: "ZEEKR 8X Ultra+",
    year: 2026,
    price: "",
    exteriorColor: "Лунно-Морской Серый",
    interiorColor: "Белый И Чёрный",
    colorCategory: "Gray",
    configuration: "",
    location: "Нинбо",
    exwPrice: "Матовый: $70 881; Ночной: /",
    notes: "",
    battery: "70kWh",
    wheels: "22-Дюймовые Сияющие Колёсные Диски С Четырехпоршневыми Тормозными Суппортами Brembo（huiyao)",
    packages: "Qianli Haohan H7, Электроподножки, Пакет Потолочных Экранов Задних Сидений, Аудио Naim Premium, Двойной центральный экран",
    image: "/images/cars/zeekr-8x-ultra-gray.jpg",
    category: "zeekr-8x-ningbo",
  },
  {
    id: "zeekr-8x-ningbo-zeekr-ultra-19",
    brand: "ZEEKR",
    model: "8X Ultra+",
    fullModel: "ZEEKR 8X Ultra+",
    year: 2026,
    price: "",
    exteriorColor: "Красный",
    interiorColor: "Белый И Чёрный",
    colorCategory: "Red",
    configuration: "",
    location: "Нинбо",
    exwPrice: "Матовый: $70 881; Ночной: /",
    notes: "",
    battery: "70kWh",
    wheels: "22-Дюймовые Сияющие Колёсные Диски С Четырехпоршневыми Тормозными Суппортами Brembo（huiyao)",
    packages: "Qianli Haohan H7, Электроподножки, Пакет Потолочных Экранов Задних Сидений, Аудио Naim Premium, Двойной центральный экран",
    image: "/images/cars/zeekr-8x-ultra-red.jpg",
    category: "zeekr-8x-ningbo",
  },
  {
    id: "zeekr-8x-ningbo-zeekr-ultra-20",
    brand: "ZEEKR",
    model: "8X Ultra+",
    fullModel: "ZEEKR 8X Ultra+",
    year: 2026,
    price: "",
    exteriorColor: "Красный",
    interiorColor: "Алый Тёмно-Красный",
    colorCategory: "Red",
    configuration: "",
    location: "Нинбо",
    exwPrice: "Матовый: $70 881; Ночной: /",
    notes: "",
    battery: "70kWh",
    wheels: "22-Дюймовые Сияющие Колёсные Диски С Четырехпоршневыми Тормозными Суппортами Brembo（huiyao)",
    packages: "Qianli Haohan H7, Электроподножки, Пакет Потолочных Экранов Задних Сидений, Аудио Naim Premium, Двойной центральный экран",
    image: "/images/cars/zeekr-8x-ultra-red.jpg",
    category: "zeekr-8x-ningbo",
  },
  {
    id: "zeekr-8x-ningbo-zeekr-ultra-21",
    brand: "ZEEKR",
    model: "8X Ultra+",
    fullModel: "ZEEKR 8X Ultra+",
    year: 2026,
    price: "",
    exteriorColor: "Красный",
    interiorColor: "Чистый Чёрный",
    colorCategory: "Red",
    configuration: "",
    location: "Нинбо",
    exwPrice: "Матовый: $70 881; Ночной: /",
    notes: "",
    battery: "70kWh",
    wheels: "22-Дюймовые Сияющие Колёсные Диски С Четырехпоршневыми Тормозными Суппортами Brembo（huiyao)",
    packages: "Qianli Haohan H7, Электроподножки, Пакет Потолочных Экранов Задних Сидений, Аудио Naim Premium, Двойной центральный экран",
    image: "/images/cars/zeekr-8x-ultra-red.jpg",
    category: "zeekr-8x-ningbo",
  },
  {
    id: "zeekr-8x-ningbo-zeekr-ultra-22",
    brand: "ZEEKR",
    model: "8X Ultra",
    fullModel: "ZEEKR 8X Ultra",
    year: 2026,
    price: "",
    exteriorColor: "Чёрный",
    interiorColor: "Белый И Чёрный",
    colorCategory: "Black",
    configuration: "",
    location: "Нинбо",
    exwPrice: "Матовый: $64 319; Ночной: $66 941",
    notes: "",
    battery: "55kWh",
    wheels: "21-Дюймовые Двухтонные Колёсные Диски С Тормозными Суппортами Brembo На Четыре Поршня（shuangyao)",
    packages: "Qianli Haohan H7, Электроподножки, Пакет Потолочных Экранов Задних Сидений, Аудио Naim Premium, Двойной центральный экран",
    image: "/images/cars/zeekr-8x-ultra-black.jpg",
    category: "zeekr-8x-ningbo",
  },
  {
    id: "zeekr-8x-ningbo-zeekr-ultra-23",
    brand: "ZEEKR",
    model: "8X Ultra",
    fullModel: "ZEEKR 8X Ultra",
    year: 2026,
    price: "",
    exteriorColor: "Чёрный",
    interiorColor: "Белый И Чёрный",
    colorCategory: "Black",
    configuration: "",
    location: "Нинбо",
    exwPrice: "Матовый: $64 319; Ночной: $66 941",
    notes: "",
    battery: "55kWh",
    wheels: "21-Дюймовые Звёздно-Сияющие Спортивные Колёсные Диски С Четырехпоршневыми Тормозными Суппортами Brembo（xingyao)",
    packages: "Qianli Haohan H7, Электроподножки, Пакет Потолочных Экранов Задних Сидений, Аудио Naim Premium, Двойной центральный экран",
    image: "/images/cars/zeekr-8x-ultra-black.jpg",
    category: "zeekr-8x-ningbo",
  },
  {
    id: "zeekr-8x-ningbo-zeekr-ultra-24",
    brand: "ZEEKR",
    model: "8X Ultra",
    fullModel: "ZEEKR 8X Ultra",
    year: 2026,
    price: "",
    exteriorColor: "Чёрный",
    interiorColor: "Чистый Чёрный",
    colorCategory: "Black",
    configuration: "",
    location: "Нинбо",
    exwPrice: "Матовый: $64 319; Ночной: $66 941",
    notes: "",
    battery: "55kWh",
    wheels: "21-Дюймовые Двухтонные Колёсные Диски С Тормозными Суппортами Brembo На Четыре Поршня（shuangyao)",
    packages: "Qianli Haohan H7, Электроподножки, Пакет Потолочных Экранов Задних Сидений, Аудио Naim Premium, Двойной центральный экран",
    image: "/images/cars/zeekr-8x-ultra-black.jpg",
    category: "zeekr-8x-ningbo",
  },
  {
    id: "zeekr-8x-ningbo-zeekr-ultra-25",
    brand: "ZEEKR",
    model: "8X Ultra",
    fullModel: "ZEEKR 8X Ultra",
    year: 2026,
    price: "",
    exteriorColor: "Чёрный",
    interiorColor: "Чистый Чёрный",
    colorCategory: "Black",
    configuration: "",
    location: "Нинбо",
    exwPrice: "Матовый: $64 319; Ночной: $66 941",
    notes: "",
    battery: "55kWh",
    wheels: "21-Дюймовые Звёздно-Сияющие Спортивные Колёсные Диски С Четырехпоршневыми Тормозными Суппортами Brembo（xingyao)",
    packages: "Qianli Haohan H7, Электроподножки, Пакет Потолочных Экранов Задних Сидений, Аудио Naim Premium, Двойной центральный экран",
    image: "/images/cars/zeekr-8x-ultra-black.jpg",
    category: "zeekr-8x-ningbo",
  },
  {
    id: "zeekr-8x-ningbo-zeekr-ultra-26",
    brand: "ZEEKR",
    model: "8X Ultra",
    fullModel: "ZEEKR 8X Ultra",
    year: 2026,
    price: "",
    exteriorColor: "Чёрный",
    interiorColor: "Коричневый И Чёрный",
    colorCategory: "Black",
    configuration: "",
    location: "Нинбо",
    exwPrice: "Матовый: $64 319; Ночной: $66 941",
    notes: "",
    battery: "55kWh",
    wheels: "21-Дюймовые Двухтонные Колёсные Диски С Тормозными Суппортами Brembo На Четыре Поршня（shuangyao)",
    packages: "Qianli Haohan H7, Электроподножки, Пакет Потолочных Экранов Задних Сидений, Аудио Naim Premium, Двойной центральный экран",
    image: "/images/cars/zeekr-8x-ultra-black.jpg",
    category: "zeekr-8x-ningbo",
  },
  {
    id: "zeekr-8x-ningbo-zeekr-ultra-27",
    brand: "ZEEKR",
    model: "8X Ultra",
    fullModel: "ZEEKR 8X Ultra",
    year: 2026,
    price: "",
    exteriorColor: "Белый",
    interiorColor: "Чистый Чёрный",
    colorCategory: "White",
    configuration: "",
    location: "Нинбо",
    exwPrice: "Матовый: $64 319; Ночной: /",
    notes: "",
    battery: "55kWh",
    wheels: "21-Дюймовые Двухтонные Колёсные Диски С Тормозными Суппортами Brembo На Четыре Поршня（shuangyao)",
    packages: "Qianli Haohan H7, Электроподножки, Пакет Потолочных Экранов Задних Сидений, Аудио Naim Premium, Двойной центральный экран",
    image: "/images/cars/zeekr-8x-ultra-white.jpg",
    category: "zeekr-8x-ningbo",
  },
  {
    id: "zeekr-8x-ningbo-zeekr-ultra-28",
    brand: "ZEEKR",
    model: "8X Ultra",
    fullModel: "ZEEKR 8X Ultra",
    year: 2026,
    price: "",
    exteriorColor: "Белый",
    interiorColor: "Чистый Чёрный",
    colorCategory: "White",
    configuration: "",
    location: "Нинбо",
    exwPrice: "Матовый: $64 319; Ночной: /",
    notes: "",
    battery: "55kWh",
    wheels: "21-Дюймовые Звёздно-Сияющие Спортивные Колёсные Диски С Четырехпоршневыми Тормозными Суппортами Brembo（xingyao)",
    packages: "Qianli Haohan H7, Электроподножки, Пакет Потолочных Экранов Задних Сидений, Аудио Naim Premium, Двойной центральный экран",
    image: "/images/cars/zeekr-8x-ultra-white.jpg",
    category: "zeekr-8x-ningbo",
  },
  {
    id: "zeekr-8x-ningbo-zeekr-ultra-29",
    brand: "ZEEKR",
    model: "8X Ultra",
    fullModel: "ZEEKR 8X Ultra",
    year: 2026,
    price: "",
    exteriorColor: "Лунно-Морской Серый",
    interiorColor: "Белый И Чёрный",
    colorCategory: "Gray",
    configuration: "",
    location: "Нинбо",
    exwPrice: "Матовый: $64 319; Ночной: /",
    notes: "",
    battery: "55kWh",
    wheels: "21-Дюймовые Двухтонные Колёсные Диски С Тормозными Суппортами Brembo На Четыре Поршня（shuangyao)",
    packages: "Qianli Haohan H7, Электроподножки, Пакет Потолочных Экранов Задних Сидений, Аудио Naim Premium, Двойной центральный экран",
    image: "/images/cars/zeekr-8x-ultra-gray.jpg",
    category: "zeekr-8x-ningbo",
  },
  {
    id: "zeekr-8x-ningbo-zeekr-ultra-30",
    brand: "ZEEKR",
    model: "8X Ultra",
    fullModel: "ZEEKR 8X Ultra",
    year: 2026,
    price: "",
    exteriorColor: "Лунно-Морской Серый",
    interiorColor: "Белый И Чёрный",
    colorCategory: "Gray",
    configuration: "",
    location: "Нинбо",
    exwPrice: "Матовый: $64 319; Ночной: /",
    notes: "",
    battery: "55kWh",
    wheels: "21-Дюймовые Звёздно-Сияющие Спортивные Колёсные Диски С Четырехпоршневыми Тормозными Суппортами Brembo（xingyao)",
    packages: "Qianli Haohan H7, Электроподножки, Пакет Потолочных Экранов Задних Сидений, Аудио Naim Premium, Двойной центральный экран",
    image: "/images/cars/zeekr-8x-ultra-gray.jpg",
    category: "zeekr-8x-ningbo",
  },
  {
    id: "zeekr-8x-ningbo-zeekr-ultra-31",
    brand: "ZEEKR",
    model: "8X Ultra",
    fullModel: "ZEEKR 8X Ultra",
    year: 2026,
    price: "",
    exteriorColor: "Лунно-Морской Серый",
    interiorColor: "Чистый Чёрный",
    colorCategory: "Gray",
    configuration: "",
    location: "Нинбо",
    exwPrice: "Матовый: $64 319; Ночной: /",
    notes: "",
    battery: "55kWh",
    wheels: "21-Дюймовые Двухтонные Колёсные Диски С Тормозными Суппортами Brembo На Четыре Поршня（shuangyao)",
    packages: "Qianli Haohan H7, Электроподножки, Пакет Потолочных Экранов Задних Сидений, Аудио Naim Premium, Двойной центральный экран",
    image: "/images/cars/zeekr-8x-ultra-gray.jpg",
    category: "zeekr-8x-ningbo",
  },
  {
    id: "zeekr-8x-ningbo-zeekr-ultra-32",
    brand: "ZEEKR",
    model: "8X Ultra",
    fullModel: "ZEEKR 8X Ultra",
    year: 2026,
    price: "",
    exteriorColor: "Лунно-Морской Серый",
    interiorColor: "Чистый Чёрный",
    colorCategory: "Gray",
    configuration: "",
    location: "Нинбо",
    exwPrice: "Матовый: $64 319; Ночной: /",
    notes: "",
    battery: "55kWh",
    wheels: "21-Дюймовые Звёздно-Сияющие Спортивные Колёсные Диски С Четырехпоршневыми Тормозными Суппортами Brembo（xingyao)",
    packages: "Qianli Haohan H7, Электроподножки, Пакет Потолочных Экранов Задних Сидений, Аудио Naim Premium, Двойной центральный экран",
    image: "/images/cars/zeekr-8x-ultra-gray.jpg",
    category: "zeekr-8x-ningbo",
  },
  {
    id: "zeekr-8x-ningbo-zeekr-ultra-33",
    brand: "ZEEKR",
    model: "8X Ultra",
    fullModel: "ZEEKR 8X Ultra",
    year: 2026,
    price: "",
    exteriorColor: "Красный",
    interiorColor: "Алый Тёмно-Красный",
    colorCategory: "Red",
    configuration: "",
    location: "Нинбо",
    exwPrice: "Матовый: $64 319; Ночной: /",
    notes: "",
    battery: "55kWh",
    wheels: "21-Дюймовые Двухтонные Колёсные Диски С Тормозными Суппортами Brembo На Четыре Поршня（shuangyao)",
    packages: "Qianli Haohan H7, Электроподножки, Пакет Потолочных Экранов Задних Сидений, Аудио Naim Premium, Двойной центральный экран",
    image: "/images/cars/zeekr-8x-ultra-red.jpg",
    category: "zeekr-8x-ningbo",
  },
  {
    id: "zeekr-8x-ningbo-zeekr-ultra-34",
    brand: "ZEEKR",
    model: "8X Ultra",
    fullModel: "ZEEKR 8X Ultra",
    year: 2026,
    price: "",
    exteriorColor: "Красный",
    interiorColor: "Алый Тёмно-Красный",
    colorCategory: "Red",
    configuration: "",
    location: "Нинбо",
    exwPrice: "Матовый: $64 319; Ночной: /",
    notes: "",
    battery: "55kWh",
    wheels: "21-Дюймовые Звёздно-Сияющие Спортивные Колёсные Диски С Четырехпоршневыми Тормозными Суппортами Brembo（xingyao)",
    packages: "Qianli Haohan H7, Электроподножки, Пакет Потолочных Экранов Задних Сидений, Аудио Naim Premium, Двойной центральный экран",
    image: "/images/cars/zeekr-8x-ultra-red.jpg",
    category: "zeekr-8x-ningbo",
  },
  {
    id: "zeekr-8x-ningbo-zeekr-ultra-35",
    brand: "ZEEKR",
    model: "8X Ultra",
    fullModel: "ZEEKR 8X Ultra",
    year: 2026,
    price: "",
    exteriorColor: "Красный",
    interiorColor: "Чистый Чёрный",
    colorCategory: "Red",
    configuration: "",
    location: "Нинбо",
    exwPrice: "Матовый: $64 319; Ночной: /",
    notes: "",
    battery: "55kWh",
    wheels: "21-Дюймовые Двухтонные Колёсные Диски С Тормозными Суппортами Brembo На Четыре Поршня（shuangyao)",
    packages: "Qianli Haohan H7, Электроподножки, Пакет Потолочных Экранов Задних Сидений, Аудио Naim Premium, Двойной центральный экран",
    image: "/images/cars/zeekr-8x-ultra-red.jpg",
    category: "zeekr-8x-ningbo",
  },
  {
    id: "zeekr-8x-ningbo-zeekr-ultra-36",
    brand: "ZEEKR",
    model: "8X Ultra",
    fullModel: "ZEEKR 8X Ultra",
    year: 2026,
    price: "",
    exteriorColor: "Красный",
    interiorColor: "Чистый Чёрный",
    colorCategory: "Red",
    configuration: "",
    location: "Нинбо",
    exwPrice: "Матовый: $64 319; Ночной: /",
    notes: "",
    battery: "55kWh",
    wheels: "21-Дюймовые Звёздно-Сияющие Спортивные Колёсные Диски С Четырехпоршневыми Тормозными Суппортами Brembo（xingyao)",
    packages: "Qianli Haohan H7, Электроподножки, Пакет Потолочных Экранов Задних Сидений, Аудио Naim Premium, Двойной центральный экран",
    image: "/images/cars/zeekr-8x-ultra-red.jpg",
    category: "zeekr-8x-ningbo",
  },
  {
    id: "zeekr-8x-ningbo-zeekr-ultra-37",
    brand: "ZEEKR",
    model: "8X Ultra",
    fullModel: "ZEEKR 8X Ultra",
    year: 2026,
    price: "",
    exteriorColor: "Красный",
    interiorColor: "Коричневый И Чёрный",
    colorCategory: "Red",
    configuration: "",
    location: "Нинбо",
    exwPrice: "Матовый: $64 319; Ночной: /",
    notes: "",
    battery: "55kWh",
    wheels: "21-Дюймовые Двухтонные Колёсные Диски С Тормозными Суппортами Brembo На Четыре Поршня（shuangyao)",
    packages: "Qianli Haohan H7, Электроподножки, Пакет Потолочных Экранов Задних Сидений, Аудио Naim Premium, Двойной центральный экран",
    image: "/images/cars/zeekr-8x-ultra-red.jpg",
    category: "zeekr-8x-ningbo",
  },
  {
    id: "zeekr-8x-ningbo-zeekr-ultra-38",
    brand: "ZEEKR",
    model: "8X Ultra",
    fullModel: "ZEEKR 8X Ultra",
    year: 2026,
    price: "",
    exteriorColor: "Чёрный",
    interiorColor: "Белый И Чёрный",
    colorCategory: "Black",
    configuration: "",
    location: "Нинбо",
    exwPrice: "Матовый: $67 285; Ночной: $68 907",
    notes: "",
    battery: "70kWh",
    wheels: "21\" Аэродинамические Диски, Суппорты Brembo 4-Поршневые",
    packages: "Qianli Haohan H7, Электроподножки, Пакет Потолочных Экранов Задних Сидений, Аудио Naim Premium, Двойной центральный экран",
    image: "/images/cars/zeekr-8x-ultra-black.jpg",
    category: "zeekr-8x-ningbo",
  },
  {
    id: "zeekr-8x-ningbo-zeekr-ultra-39",
    brand: "ZEEKR",
    model: "8X Ultra",
    fullModel: "ZEEKR 8X Ultra",
    year: 2026,
    price: "",
    exteriorColor: "Чёрный",
    interiorColor: "Белый И Чёрный",
    colorCategory: "Black",
    configuration: "",
    location: "Нинбо",
    exwPrice: "Матовый: $67 285; Ночной: $68 907",
    notes: "",
    battery: "70kWh",
    wheels: "21-Дюймовые Двухтонные Колёсные Диски С Тормозными Суппортами Brembo На Четыре Поршня（shuangyao)",
    packages: "Qianli Haohan H7, Электроподножки, Пакет Потолочных Экранов Задних Сидений, Аудио Naim Premium, Двойной центральный экран",
    image: "/images/cars/zeekr-8x-ultra-black.jpg",
    category: "zeekr-8x-ningbo",
  },
  {
    id: "zeekr-8x-ningbo-zeekr-ultra-40",
    brand: "ZEEKR",
    model: "8X Ultra",
    fullModel: "ZEEKR 8X Ultra",
    year: 2026,
    price: "",
    exteriorColor: "Чёрный",
    interiorColor: "Алый Тёмно-Красный",
    colorCategory: "Black",
    configuration: "",
    location: "Нинбо",
    exwPrice: "Матовый: $67 285; Ночной: $68 907",
    notes: "",
    battery: "70kWh",
    wheels: "21\" Аэродинамические Диски, Суппорты Brembo 4-Поршневые",
    packages: "Qianli Haohan H7, Электроподножки, Пакет Потолочных Экранов Задних Сидений, Аудио Naim Premium, Двойной центральный экран",
    image: "/images/cars/zeekr-8x-ultra-black.jpg",
    category: "zeekr-8x-ningbo",
  },
  {
    id: "zeekr-8x-ningbo-zeekr-ultra-41",
    brand: "ZEEKR",
    model: "8X Ultra",
    fullModel: "ZEEKR 8X Ultra",
    year: 2026,
    price: "",
    exteriorColor: "Чёрный",
    interiorColor: "Алый Тёмно-Красный",
    colorCategory: "Black",
    configuration: "",
    location: "Нинбо",
    exwPrice: "Матовый: $67 285; Ночной: $68 907",
    notes: "",
    battery: "70kWh",
    wheels: "21-Дюймовые Двухтонные Колёсные Диски С Тормозными Суппортами Brembo На Четыре Поршня（shuangyao)",
    packages: "Qianli Haohan H7, Электроподножки, Пакет Потолочных Экранов Задних Сидений, Аудио Naim Premium, Двойной центральный экран",
    image: "/images/cars/zeekr-8x-ultra-black.jpg",
    category: "zeekr-8x-ningbo",
  },
  {
    id: "zeekr-8x-ningbo-zeekr-ultra-42",
    brand: "ZEEKR",
    model: "8X Ultra",
    fullModel: "ZEEKR 8X Ultra",
    year: 2026,
    price: "",
    exteriorColor: "Чёрный",
    interiorColor: "Алый Тёмно-Красный",
    colorCategory: "Black",
    configuration: "",
    location: "Нинбо",
    exwPrice: "Матовый: $67 285; Ночной: $68 907",
    notes: "",
    battery: "70kWh",
    wheels: "21-Дюймовые Звёздно-Сияющие Спортивные Колёсные Диски С Четырехпоршневыми Тормозными Суппортами Brembo（xingyao)",
    packages: "Qianli Haohan H7, Электроподножки, Пакет Потолочных Экранов Задних Сидений, Аудио Naim Premium, Двойной центральный экран",
    image: "/images/cars/zeekr-8x-ultra-black.jpg",
    category: "zeekr-8x-ningbo",
  },
  {
    id: "zeekr-8x-ningbo-zeekr-ultra-43",
    brand: "ZEEKR",
    model: "8X Ultra",
    fullModel: "ZEEKR 8X Ultra",
    year: 2026,
    price: "",
    exteriorColor: "Чёрный",
    interiorColor: "Чистый Чёрный",
    colorCategory: "Black",
    configuration: "",
    location: "Нинбо",
    exwPrice: "Матовый: $67 285; Ночной: $68 907",
    notes: "",
    battery: "70kWh",
    wheels: "21\" Аэродинамические Диски, Суппорты Brembo 4-Поршневые",
    packages: "Qianli Haohan H7, Электроподножки, Пакет Потолочных Экранов Задних Сидений, Аудио Naim Premium, Двойной центральный экран",
    image: "/images/cars/zeekr-8x-ultra-black.jpg",
    category: "zeekr-8x-ningbo",
  },
  {
    id: "zeekr-8x-ningbo-zeekr-ultra-44",
    brand: "ZEEKR",
    model: "8X Ultra",
    fullModel: "ZEEKR 8X Ultra",
    year: 2026,
    price: "",
    exteriorColor: "Чёрный",
    interiorColor: "Чистый Чёрный",
    colorCategory: "Black",
    configuration: "",
    location: "Нинбо",
    exwPrice: "Матовый: $67 285; Ночной: $68 907",
    notes: "",
    battery: "70kWh",
    wheels: "21-Дюймовые Двухтонные Колёсные Диски С Тормозными Суппортами Brembo На Четыре Поршня（shuangyao)",
    packages: "Qianli Haohan H7, Электроподножки, Пакет Потолочных Экранов Задних Сидений, Аудио Naim Premium, Двойной центральный экран",
    image: "/images/cars/zeekr-8x-ultra-black.jpg",
    category: "zeekr-8x-ningbo",
  },
  {
    id: "zeekr-8x-ningbo-zeekr-ultra-45",
    brand: "ZEEKR",
    model: "8X Ultra",
    fullModel: "ZEEKR 8X Ultra",
    year: 2026,
    price: "",
    exteriorColor: "Чёрный",
    interiorColor: "Чистый Чёрный",
    colorCategory: "Black",
    configuration: "",
    location: "Нинбо",
    exwPrice: "Матовый: $67 285; Ночной: $68 907",
    notes: "",
    battery: "70kWh",
    wheels: "21-Дюймовые Звёздно-Сияющие Спортивные Колёсные Диски С Четырехпоршневыми Тормозными Суппортами Brembo（xingyao)",
    packages: "Qianli Haohan H7, Электроподножки, Пакет Потолочных Экранов Задних Сидений, Аудио Naim Premium, Двойной центральный экран",
    image: "/images/cars/zeekr-8x-ultra-black.jpg",
    category: "zeekr-8x-ningbo",
  },
  {
    id: "zeekr-8x-ningbo-zeekr-ultra-46",
    brand: "ZEEKR",
    model: "8X Ultra",
    fullModel: "ZEEKR 8X Ultra",
    year: 2026,
    price: "",
    exteriorColor: "Чёрный",
    interiorColor: "Коричневый И Чёрный",
    colorCategory: "Black",
    configuration: "",
    location: "Нинбо",
    exwPrice: "Матовый: $67 285; Ночной: $68 907",
    notes: "",
    battery: "70kWh",
    wheels: "21\" Аэродинамические Диски, Суппорты Brembo 4-Поршневые",
    packages: "Qianli Haohan H7, Электроподножки, Пакет Потолочных Экранов Задних Сидений, Аудио Naim Premium, Двойной центральный экран",
    image: "/images/cars/zeekr-8x-ultra-black.jpg",
    category: "zeekr-8x-ningbo",
  },
  {
    id: "zeekr-8x-ningbo-zeekr-ultra-47",
    brand: "ZEEKR",
    model: "8X Ultra",
    fullModel: "ZEEKR 8X Ultra",
    year: 2026,
    price: "",
    exteriorColor: "Чёрный",
    interiorColor: "Коричневый И Чёрный",
    colorCategory: "Black",
    configuration: "",
    location: "Нинбо",
    exwPrice: "Матовый: $67 285; Ночной: $68 907",
    notes: "",
    battery: "70kWh",
    wheels: "21-Дюймовые Двухтонные Колёсные Диски С Тормозными Суппортами Brembo На Четыре Поршня（shuangyao)",
    packages: "Qianli Haohan H7, Электроподножки, Пакет Потолочных Экранов Задних Сидений, Аудио Naim Premium, Двойной центральный экран",
    image: "/images/cars/zeekr-8x-ultra-black.jpg",
    category: "zeekr-8x-ningbo",
  },
  {
    id: "zeekr-8x-ningbo-zeekr-ultra-48",
    brand: "ZEEKR",
    model: "8X Ultra",
    fullModel: "ZEEKR 8X Ultra",
    year: 2026,
    price: "",
    exteriorColor: "Белый",
    interiorColor: "Белый И Чёрный",
    colorCategory: "White",
    configuration: "",
    location: "Нинбо",
    exwPrice: "Матовый: $67 285; Ночной: /",
    notes: "",
    battery: "70kWh",
    wheels: "21\" Аэродинамические Диски, Суппорты Brembo 4-Поршневые",
    packages: "Qianli Haohan H7, Электроподножки, Пакет Потолочных Экранов Задних Сидений, Аудио Naim Premium, Двойной центральный экран",
    image: "/images/cars/zeekr-8x-ultra-white.jpg",
    category: "zeekr-8x-ningbo",
  },
  {
    id: "zeekr-8x-ningbo-zeekr-ultra-49",
    brand: "ZEEKR",
    model: "8X Ultra",
    fullModel: "ZEEKR 8X Ultra",
    year: 2026,
    price: "",
    exteriorColor: "Белый",
    interiorColor: "Белый И Чёрный",
    colorCategory: "White",
    configuration: "",
    location: "Нинбо",
    exwPrice: "Матовый: $67 285; Ночной: /",
    notes: "",
    battery: "70kWh",
    wheels: "21-Дюймовые Двухтонные Колёсные Диски С Тормозными Суппортами Brembo На Четыре Поршня（shuangyao)",
    packages: "Qianli Haohan H7, Электроподножки, Пакет Потолочных Экранов Задних Сидений, Аудио Naim Premium, Двойной центральный экран",
    image: "/images/cars/zeekr-8x-ultra-white.jpg",
    category: "zeekr-8x-ningbo",
  },
  {
    id: "zeekr-8x-ningbo-zeekr-ultra-50",
    brand: "ZEEKR",
    model: "8X Ultra",
    fullModel: "ZEEKR 8X Ultra",
    year: 2026,
    price: "",
    exteriorColor: "Белый",
    interiorColor: "Алый Тёмно-Красный",
    colorCategory: "White",
    configuration: "",
    location: "Нинбо",
    exwPrice: "Матовый: $67 285; Ночной: /",
    notes: "",
    battery: "70kWh",
    wheels: "21\" Аэродинамические Диски, Суппорты Brembo 4-Поршневые",
    packages: "Qianli Haohan H7, Электроподножки, Пакет Потолочных Экранов Задних Сидений, Аудио Naim Premium, Двойной центральный экран",
    image: "/images/cars/zeekr-8x-ultra-white.jpg",
    category: "zeekr-8x-ningbo",
  },
  {
    id: "zeekr-8x-ningbo-zeekr-ultra-51",
    brand: "ZEEKR",
    model: "8X Ultra",
    fullModel: "ZEEKR 8X Ultra",
    year: 2026,
    price: "",
    exteriorColor: "Белый",
    interiorColor: "Чистый Чёрный",
    colorCategory: "White",
    configuration: "",
    location: "Нинбо",
    exwPrice: "Матовый: $67 285; Ночной: /",
    notes: "",
    battery: "70kWh",
    wheels: "21\" Аэродинамические Диски, Суппорты Brembo 4-Поршневые",
    packages: "Qianli Haohan H7, Электроподножки, Пакет Потолочных Экранов Задних Сидений, Аудио Naim Premium, Двойной центральный экран",
    image: "/images/cars/zeekr-8x-ultra-white.jpg",
    category: "zeekr-8x-ningbo",
  },
  {
    id: "zeekr-8x-ningbo-zeekr-ultra-52",
    brand: "ZEEKR",
    model: "8X Ultra",
    fullModel: "ZEEKR 8X Ultra",
    year: 2026,
    price: "",
    exteriorColor: "Белый",
    interiorColor: "Чистый Чёрный",
    colorCategory: "White",
    configuration: "",
    location: "Нинбо",
    exwPrice: "Матовый: $67 285; Ночной: /",
    notes: "",
    battery: "70kWh",
    wheels: "21-Дюймовые Двухтонные Колёсные Диски С Тормозными Суппортами Brembo На Четыре Поршня（shuangyao)",
    packages: "Qianli Haohan H7, Электроподножки, Пакет Потолочных Экранов Задних Сидений, Аудио Naim Premium, Двойной центральный экран",
    image: "/images/cars/zeekr-8x-ultra-white.jpg",
    category: "zeekr-8x-ningbo",
  },
  {
    id: "zeekr-8x-ningbo-zeekr-ultra-53",
    brand: "ZEEKR",
    model: "8X Ultra",
    fullModel: "ZEEKR 8X Ultra",
    year: 2026,
    price: "",
    exteriorColor: "Белый",
    interiorColor: "Коричневый И Чёрный",
    colorCategory: "White",
    configuration: "",
    location: "Нинбо",
    exwPrice: "Матовый: $67 285; Ночной: /",
    notes: "",
    battery: "70kWh",
    wheels: "21\" Аэродинамические Диски, Суппорты Brembo 4-Поршневые",
    packages: "Qianli Haohan H7, Электроподножки, Пакет Потолочных Экранов Задних Сидений, Аудио Naim Premium, Двойной центральный экран",
    image: "/images/cars/zeekr-8x-ultra-white.jpg",
    category: "zeekr-8x-ningbo",
  },
  {
    id: "zeekr-8x-ningbo-zeekr-ultra-54",
    brand: "ZEEKR",
    model: "8X Ultra",
    fullModel: "ZEEKR 8X Ultra",
    year: 2026,
    price: "",
    exteriorColor: "Белый",
    interiorColor: "Коричневый И Чёрный",
    colorCategory: "White",
    configuration: "",
    location: "Нинбо",
    exwPrice: "Матовый: $67 285; Ночной: /",
    notes: "",
    battery: "70kWh",
    wheels: "21-Дюймовые Двухтонные Колёсные Диски С Тормозными Суппортами Brembo На Четыре Поршня（shuangyao)",
    packages: "Qianli Haohan H7, Электроподножки, Пакет Потолочных Экранов Задних Сидений, Аудио Naim Premium, Двойной центральный экран",
    image: "/images/cars/zeekr-8x-ultra-white.jpg",
    category: "zeekr-8x-ningbo",
  },
  {
    id: "zeekr-8x-ningbo-zeekr-ultra-55",
    brand: "ZEEKR",
    model: "8X Ultra",
    fullModel: "ZEEKR 8X Ultra",
    year: 2026,
    price: "",
    exteriorColor: "Лунно-Морской Серый",
    interiorColor: "Белый И Чёрный",
    colorCategory: "Gray",
    configuration: "",
    location: "Нинбо",
    exwPrice: "Матовый: $67 285; Ночной: /",
    notes: "",
    battery: "70kWh",
    wheels: "21\" Аэродинамические Диски, Суппорты Brembo 4-Поршневые",
    packages: "Qianli Haohan H7, Электроподножки, Пакет Потолочных Экранов Задних Сидений, Аудио Naim Premium, Двойной центральный экран",
    image: "/images/cars/zeekr-8x-ultra-gray.jpg",
    category: "zeekr-8x-ningbo",
  },
  {
    id: "zeekr-8x-ningbo-zeekr-ultra-56",
    brand: "ZEEKR",
    model: "8X Ultra",
    fullModel: "ZEEKR 8X Ultra",
    year: 2026,
    price: "",
    exteriorColor: "Лунно-Морской Серый",
    interiorColor: "Белый И Чёрный",
    colorCategory: "Gray",
    configuration: "",
    location: "Нинбо",
    exwPrice: "Матовый: $67 285; Ночной: /",
    notes: "",
    battery: "70kWh",
    wheels: "21-Дюймовые Двухтонные Колёсные Диски С Тормозными Суппортами Brembo На Четыре Поршня（shuangyao)",
    packages: "Qianli Haohan H7, Электроподножки, Пакет Потолочных Экранов Задних Сидений, Аудио Naim Premium, Двойной центральный экран",
    image: "/images/cars/zeekr-8x-ultra-gray.jpg",
    category: "zeekr-8x-ningbo",
  },
  {
    id: "zeekr-8x-ningbo-zeekr-ultra-57",
    brand: "ZEEKR",
    model: "8X Ultra",
    fullModel: "ZEEKR 8X Ultra",
    year: 2026,
    price: "",
    exteriorColor: "Лунно-Морской Серый",
    interiorColor: "Алый Тёмно-Красный",
    colorCategory: "Gray",
    configuration: "",
    location: "Нинбо",
    exwPrice: "Матовый: $67 285; Ночной: /",
    notes: "",
    battery: "70kWh",
    wheels: "21\" Аэродинамические Диски, Суппорты Brembo 4-Поршневые",
    packages: "Qianli Haohan H7, Электроподножки, Пакет Потолочных Экранов Задних Сидений, Аудио Naim Premium, Двойной центральный экран",
    image: "/images/cars/zeekr-8x-ultra-gray.jpg",
    category: "zeekr-8x-ningbo",
  },
  {
    id: "zeekr-8x-ningbo-zeekr-ultra-58",
    brand: "ZEEKR",
    model: "8X Ultra",
    fullModel: "ZEEKR 8X Ultra",
    year: 2026,
    price: "",
    exteriorColor: "Лунно-Морской Серый",
    interiorColor: "Алый Тёмно-Красный",
    colorCategory: "Gray",
    configuration: "",
    location: "Нинбо",
    exwPrice: "Матовый: $67 285; Ночной: /",
    notes: "",
    battery: "70kWh",
    wheels: "21-Дюймовые Двухтонные Колёсные Диски С Тормозными Суппортами Brembo На Четыре Поршня（shuangyao)",
    packages: "Qianli Haohan H7, Электроподножки, Пакет Потолочных Экранов Задних Сидений, Аудио Naim Premium, Двойной центральный экран",
    image: "/images/cars/zeekr-8x-ultra-gray.jpg",
    category: "zeekr-8x-ningbo",
  },
  {
    id: "zeekr-8x-ningbo-zeekr-ultra-59",
    brand: "ZEEKR",
    model: "8X Ultra",
    fullModel: "ZEEKR 8X Ultra",
    year: 2026,
    price: "",
    exteriorColor: "Лунно-Морской Серый",
    interiorColor: "Чистый Чёрный",
    colorCategory: "Gray",
    configuration: "",
    location: "Нинбо",
    exwPrice: "Матовый: $67 285; Ночной: /",
    notes: "",
    battery: "70kWh",
    wheels: "21\" Аэродинамические Диски, Суппорты Brembo 4-Поршневые",
    packages: "Qianli Haohan H7, Электроподножки, Пакет Потолочных Экранов Задних Сидений, Аудио Naim Premium, Двойной центральный экран",
    image: "/images/cars/zeekr-8x-ultra-gray.jpg",
    category: "zeekr-8x-ningbo",
  },
  {
    id: "zeekr-8x-ningbo-zeekr-ultra-60",
    brand: "ZEEKR",
    model: "8X Ultra",
    fullModel: "ZEEKR 8X Ultra",
    year: 2026,
    price: "",
    exteriorColor: "Лунно-Морской Серый",
    interiorColor: "Чистый Чёрный",
    colorCategory: "Gray",
    configuration: "",
    location: "Нинбо",
    exwPrice: "Матовый: $67 285; Ночной: /",
    notes: "",
    battery: "70kWh",
    wheels: "21-Дюймовые Двухтонные Колёсные Диски С Тормозными Суппортами Brembo На Четыре Поршня（shuangyao)",
    packages: "Qianli Haohan H7, Электроподножки, Пакет Потолочных Экранов Задних Сидений, Аудио Naim Premium, Двойной центральный экран",
    image: "/images/cars/zeekr-8x-ultra-gray.jpg",
    category: "zeekr-8x-ningbo",
  },
  {
    id: "zeekr-8x-ningbo-zeekr-ultra-61",
    brand: "ZEEKR",
    model: "8X Ultra",
    fullModel: "ZEEKR 8X Ultra",
    year: 2026,
    price: "",
    exteriorColor: "Лунно-Морской Серый",
    interiorColor: "Коричневый И Чёрный",
    colorCategory: "Gray",
    configuration: "",
    location: "Нинбо",
    exwPrice: "Матовый: $67 285; Ночной: /",
    notes: "",
    battery: "70kWh",
    wheels: "21\" Аэродинамические Диски, Суппорты Brembo 4-Поршневые",
    packages: "Qianli Haohan H7, Электроподножки, Пакет Потолочных Экранов Задних Сидений, Аудио Naim Premium, Двойной центральный экран",
    image: "/images/cars/zeekr-8x-ultra-gray.jpg",
    category: "zeekr-8x-ningbo",
  },
  {
    id: "zeekr-8x-ningbo-zeekr-ultra-62",
    brand: "ZEEKR",
    model: "8X Ultra",
    fullModel: "ZEEKR 8X Ultra",
    year: 2026,
    price: "",
    exteriorColor: "Красный",
    interiorColor: "Белый И Чёрный",
    colorCategory: "Red",
    configuration: "",
    location: "Нинбо",
    exwPrice: "Матовый: $67 285; Ночной: /",
    notes: "",
    battery: "70kWh",
    wheels: "21\" Аэродинамические Диски, Суппорты Brembo 4-Поршневые",
    packages: "Qianli Haohan H7, Электроподножки, Пакет Потолочных Экранов Задних Сидений, Аудио Naim Premium, Двойной центральный экран",
    image: "/images/cars/zeekr-8x-ultra-red.jpg",
    category: "zeekr-8x-ningbo",
  },
  {
    id: "zeekr-8x-ningbo-zeekr-ultra-63",
    brand: "ZEEKR",
    model: "8X Ultra",
    fullModel: "ZEEKR 8X Ultra",
    year: 2026,
    price: "",
    exteriorColor: "Красный",
    interiorColor: "Белый И Чёрный",
    colorCategory: "Red",
    configuration: "",
    location: "Нинбо",
    exwPrice: "Матовый: $67 285; Ночной: /",
    notes: "",
    battery: "70kWh",
    wheels: "21-Дюймовые Двухтонные Колёсные Диски С Тормозными Суппортами Brembo На Четыре Поршня（shuangyao)",
    packages: "Qianli Haohan H7, Электроподножки, Пакет Потолочных Экранов Задних Сидений, Аудио Naim Premium, Двойной центральный экран",
    image: "/images/cars/zeekr-8x-ultra-red.jpg",
    category: "zeekr-8x-ningbo",
  },
  {
    id: "zeekr-8x-ningbo-zeekr-ultra-64",
    brand: "ZEEKR",
    model: "8X Ultra",
    fullModel: "ZEEKR 8X Ultra",
    year: 2026,
    price: "",
    exteriorColor: "Красный",
    interiorColor: "Алый Тёмно-Красный",
    colorCategory: "Red",
    configuration: "",
    location: "Нинбо",
    exwPrice: "Матовый: $67 285; Ночной: /",
    notes: "",
    battery: "70kWh",
    wheels: "21\" Аэродинамические Диски, Суппорты Brembo 4-Поршневые",
    packages: "Qianli Haohan H7, Электроподножки, Пакет Потолочных Экранов Задних Сидений, Аудио Naim Premium, Двойной центральный экран",
    image: "/images/cars/zeekr-8x-ultra-red.jpg",
    category: "zeekr-8x-ningbo",
  },
  {
    id: "zeekr-8x-ningbo-zeekr-ultra-65",
    brand: "ZEEKR",
    model: "8X Ultra",
    fullModel: "ZEEKR 8X Ultra",
    year: 2026,
    price: "",
    exteriorColor: "Красный",
    interiorColor: "Алый Тёмно-Красный",
    colorCategory: "Red",
    configuration: "",
    location: "Нинбо",
    exwPrice: "Матовый: $67 285; Ночной: /",
    notes: "",
    battery: "70kWh",
    wheels: "21-Дюймовые Двухтонные Колёсные Диски С Тормозными Суппортами Brembo На Четыре Поршня（shuangyao)",
    packages: "Qianli Haohan H7, Электроподножки, Пакет Потолочных Экранов Задних Сидений, Аудио Naim Premium, Двойной центральный экран",
    image: "/images/cars/zeekr-8x-ultra-red.jpg",
    category: "zeekr-8x-ningbo",
  },
  {
    id: "zeekr-8x-ningbo-zeekr-ultra-66",
    brand: "ZEEKR",
    model: "8X Ultra",
    fullModel: "ZEEKR 8X Ultra",
    year: 2026,
    price: "",
    exteriorColor: "Красный",
    interiorColor: "Чистый Чёрный",
    colorCategory: "Red",
    configuration: "",
    location: "Нинбо",
    exwPrice: "Матовый: $67 285; Ночной: /",
    notes: "",
    battery: "70kWh",
    wheels: "21\" Аэродинамические Диски, Суппорты Brembo 4-Поршневые",
    packages: "Qianli Haohan H7, Электроподножки, Пакет Потолочных Экранов Задних Сидений, Аудио Naim Premium, Двойной центральный экран",
    image: "/images/cars/zeekr-8x-ultra-red.jpg",
    category: "zeekr-8x-ningbo",
  },
  {
    id: "zeekr-8x-ningbo-zeekr-ultra-67",
    brand: "ZEEKR",
    model: "8X Ultra",
    fullModel: "ZEEKR 8X Ultra",
    year: 2026,
    price: "",
    exteriorColor: "Красный",
    interiorColor: "Чистый Чёрный",
    colorCategory: "Red",
    configuration: "",
    location: "Нинбо",
    exwPrice: "Матовый: $67 285; Ночной: /",
    notes: "",
    battery: "70kWh",
    wheels: "21-Дюймовые Двухтонные Колёсные Диски С Тормозными Суппортами Brembo На Четыре Поршня（shuangyao)",
    packages: "Qianli Haohan H7, Электроподножки, Пакет Потолочных Экранов Задних Сидений, Аудио Naim Premium, Двойной центральный экран",
    image: "/images/cars/zeekr-8x-ultra-red.jpg",
    category: "zeekr-8x-ningbo",
  },
  {
    id: "zeekr-8x-ningbo-zeekr-ultra-68",
    brand: "ZEEKR",
    model: "8X Ultra",
    fullModel: "ZEEKR 8X Ultra",
    year: 2026,
    price: "",
    exteriorColor: "Красный",
    interiorColor: "Чистый Чёрный",
    colorCategory: "Red",
    configuration: "",
    location: "Нинбо",
    exwPrice: "Матовый: $67 285; Ночной: /",
    notes: "",
    battery: "70kWh",
    wheels: "21-Дюймовые Звёздно-Сияющие Спортивные Колёсные Диски С Четырехпоршневыми Тормозными Суппортами Brembo（xingyao)",
    packages: "Qianli Haohan H7, Электроподножки, Пакет Потолочных Экранов Задних Сидений, Аудио Naim Premium, Двойной центральный экран",
    image: "/images/cars/zeekr-8x-ultra-red.jpg",
    category: "zeekr-8x-ningbo",
  },
  {
    id: "zeekr-8x-ningbo-zeekr-ultra-69",
    brand: "ZEEKR",
    model: "8X Ultra",
    fullModel: "ZEEKR 8X Ultra",
    year: 2026,
    price: "",
    exteriorColor: "Красный",
    interiorColor: "Коричневый И Чёрный",
    colorCategory: "Red",
    configuration: "",
    location: "Нинбо",
    exwPrice: "Матовый: $67 285; Ночной: /",
    notes: "",
    battery: "70kWh",
    wheels: "21\" Аэродинамические Диски, Суппорты Brembo 4-Поршневые",
    packages: "Qianli Haohan H7, Электроподножки, Пакет Потолочных Экранов Задних Сидений, Аудио Naim Premium, Двойной центральный экран",
    image: "/images/cars/zeekr-8x-ultra-red.jpg",
    category: "zeekr-8x-ningbo",
  },
  {
    id: "zeekr-8x-ningbo-zeekr-ultra-70",
    brand: "ZEEKR",
    model: "8X Ultra",
    fullModel: "ZEEKR 8X Ultra",
    year: 2026,
    price: "",
    exteriorColor: "Красный",
    interiorColor: "Коричневый И Чёрный",
    colorCategory: "Red",
    configuration: "",
    location: "Нинбо",
    exwPrice: "Матовый: $67 285; Ночной: /",
    notes: "",
    battery: "70kWh",
    wheels: "21-Дюймовые Двухтонные Колёсные Диски С Тормозными Суппортами Brembo На Четыре Поршня（shuangyao)",
    packages: "Qianli Haohan H7, Электроподножки, Пакет Потолочных Экранов Задних Сидений, Аудио Naim Premium, Двойной центральный экран",
    image: "/images/cars/zeekr-8x-ultra-red.jpg",
    category: "zeekr-8x-ningbo",
  },
  {
    id: "lynkco-900-lynk-co-900-20t-ultra-2026-1",
    brand: "Lynk & Co",
    model: "900 2.0T Ultra, 2026",
    fullModel: "Lynk & Co 900 2.0T Ultra, 2026",
    year: 2026,
    price: "366 900",
    exteriorColor: "Черный",
    interiorColor: "Синий",
    colorCategory: "Black",
    configuration: "Фаркоп",
    location: "Хоргос",
    exwPrice: "$47 500",
    notes: "",
    battery: "",
    wheels: "",
    packages: "",
    image: "/images/cars/lynk-and-co-900-20t-ultra-2026-black.jpg",
    category: "lynkco-900",
  },
  {
    id: "lynkco-900-lynk-co-900-20t-ultra-2026-2",
    brand: "Lynk & Co",
    model: "900 2.0T Ultra, 2026",
    fullModel: "Lynk & Co 900 2.0T Ultra, 2026",
    year: 2026,
    price: "366 900",
    exteriorColor: "Черный",
    interiorColor: "Бежевый",
    colorCategory: "Black",
    configuration: "Фаркоп",
    location: "Хоргос",
    exwPrice: "$47 500",
    notes: "",
    battery: "",
    wheels: "",
    packages: "",
    image: "/images/cars/lynk-and-co-900-20t-ultra-2026-black.jpg",
    category: "lynkco-900",
  },
  {
    id: "lynkco-900-lynk-co-900-20t-ultra-2026-3",
    brand: "Lynk & Co",
    model: "900 2.0T Ultra, 2026",
    fullModel: "Lynk & Co 900 2.0T Ultra, 2026",
    year: 2026,
    price: "366 900",
    exteriorColor: "Синий",
    interiorColor: "Синий",
    colorCategory: "Blue",
    configuration: "Фаркоп",
    location: "Хоргос",
    exwPrice: "$47 500",
    notes: "",
    battery: "",
    wheels: "",
    packages: "",
    image: "/images/cars/lynk-and-co-900-20t-ultra-2026-blue.jpg",
    category: "lynkco-900",
  },
  {
    id: "lynkco-900-lynk-co-900-20t-ultra-2026-4",
    brand: "Lynk & Co",
    model: "900 2.0T Ultra, 2026",
    fullModel: "Lynk & Co 900 2.0T Ultra, 2026",
    year: 2026,
    price: "366 900",
    exteriorColor: "Синий",
    interiorColor: "Бежевый",
    colorCategory: "Blue",
    configuration: "Без фаркопа",
    location: "Хоргос",
    exwPrice: "$47 500",
    notes: "",
    battery: "",
    wheels: "",
    packages: "",
    image: "/images/cars/lynk-and-co-900-20t-ultra-2026-blue.jpg",
    category: "lynkco-900",
  },
  {
    id: "lynkco-900-lynk-co-900-20t-ultra-2026-5",
    brand: "Lynk & Co",
    model: "900 2.0T Ultra, 2026",
    fullModel: "Lynk & Co 900 2.0T Ultra, 2026",
    year: 2026,
    price: "366 900",
    exteriorColor: "Белый",
    interiorColor: "Синий",
    colorCategory: "White",
    configuration: "Фаркоп",
    location: "Хоргос",
    exwPrice: "$47 500",
    notes: "",
    battery: "",
    wheels: "",
    packages: "",
    image: "/images/cars/lynk-and-co-900-20t-ultra-2026-white.jpg",
    category: "lynkco-900",
  },
  {
    id: "lynkco-900-lynk-co-900-20t-ultra-2026-6",
    brand: "Lynk & Co",
    model: "900 2.0T Ultra, 2026",
    fullModel: "Lynk & Co 900 2.0T Ultra, 2026",
    year: 2026,
    price: "366 900",
    exteriorColor: "Серый",
    interiorColor: "Синий",
    colorCategory: "Gray",
    configuration: "Фаркоп",
    location: "Хоргос",
    exwPrice: "$47 500",
    notes: "",
    battery: "",
    wheels: "",
    packages: "",
    image: "/images/cars/lynk-and-co-900-20t-ultra-2026-gray.jpg",
    category: "lynkco-900",
  },
  {
    id: "lynkco-900-lynk-co-900-20t-ultra-2026-7",
    brand: "Lynk & Co",
    model: "900 2.0T Ultra, 2026",
    fullModel: "Lynk & Co 900 2.0T Ultra, 2026",
    year: 2026,
    price: "366 900",
    exteriorColor: "Серый",
    interiorColor: "Бежевый",
    colorCategory: "Gray",
    configuration: "Фаркоп",
    location: "Хоргос",
    exwPrice: "$47 500",
    notes: "",
    battery: "",
    wheels: "",
    packages: "",
    image: "/images/cars/lynk-and-co-900-20t-ultra-2026-gray.jpg",
    category: "lynkco-900",
  },
  {
    id: "lynkco-900-lynk-co-900-20t-ultra-2026-8",
    brand: "Lynk & Co",
    model: "900 2.0T Ultra, 2026",
    fullModel: "Lynk & Co 900 2.0T Ultra, 2026",
    year: 2026,
    price: "366 900",
    exteriorColor: "Черный",
    interiorColor: "Бежевый",
    colorCategory: "Black",
    configuration: "Фаркоп",
    location: "Иу",
    exwPrice: "$46 600",
    notes: "",
    battery: "",
    wheels: "",
    packages: "",
    image: "/images/cars/lynk-and-co-900-20t-ultra-2026-black.jpg",
    category: "lynkco-900",
  },
  {
    id: "lynkco-900-lynk-co-900-20t-ultra-2026-9",
    brand: "Lynk & Co",
    model: "900 2.0T Ultra, 2026",
    fullModel: "Lynk & Co 900 2.0T Ultra, 2026",
    year: 2026,
    price: "366 900",
    exteriorColor: "Черный",
    interiorColor: "Оранжевый",
    colorCategory: "Black",
    configuration: "Фаркоп",
    location: "Иу",
    exwPrice: "$46 600",
    notes: "",
    battery: "",
    wheels: "",
    packages: "",
    image: "/images/cars/lynk-and-co-900-20t-ultra-2026-black.jpg",
    category: "lynkco-900",
  },
  {
    id: "lynkco-900-lynk-co-900-20t-ultra-2026-10",
    brand: "Lynk & Co",
    model: "900 2.0T Ultra, 2026",
    fullModel: "Lynk & Co 900 2.0T Ultra, 2026",
    year: 2026,
    price: "366 900",
    exteriorColor: "Белый",
    interiorColor: "Синий",
    colorCategory: "White",
    configuration: "Фаркоп",
    location: "Иу",
    exwPrice: "$46 600",
    notes: "",
    battery: "",
    wheels: "",
    packages: "",
    image: "/images/cars/lynk-and-co-900-20t-ultra-2026-white.jpg",
    category: "lynkco-900",
  },
  {
    id: "lynkco-900-lynk-co-900-15t-ultra-2026-11",
    brand: "Lynk & Co",
    model: "900 1.5T Ultra, 2026",
    fullModel: "Lynk & Co 900 1.5T Ultra, 2026",
    year: 2026,
    price: "336 900",
    exteriorColor: "Белый",
    interiorColor: "Синий",
    colorCategory: "White",
    configuration: "Фаркоп",
    location: "Иу",
    exwPrice: "$43 800",
    notes: "",
    battery: "",
    wheels: "",
    packages: "",
    image: "/images/cars/lynk-and-co-900-15t-ultra-2026-white.jpg",
    category: "lynkco-900",
  },
  {
    id: "lynkco-900-lynk-co-900-20t-ultra-2025-12",
    brand: "Lynk & Co",
    model: "900 2.0T Ultra, 2025",
    fullModel: "Lynk & Co 900 2.0T Ultra, 2025",
    year: 2025,
    price: "366 900",
    exteriorColor: "Черный",
    interiorColor: "Оранжевый",
    colorCategory: "Black",
    configuration: "Фаркоп",
    location: "Хоргос",
    exwPrice: "$43 800",
    notes: "",
    battery: "",
    wheels: "",
    packages: "",
    image: "/images/cars/lynk-and-co-900-20t-ultra-2025-black.jpg",
    category: "lynkco-900",
  },
  {
    id: "lynkco-900-lynk-co-900-20t-ultra-2025-13",
    brand: "Lynk & Co",
    model: "900 2.0T Ultra, 2025",
    fullModel: "Lynk & Co 900 2.0T Ultra, 2025",
    year: 2025,
    price: "366 900",
    exteriorColor: "Черный",
    interiorColor: "Синий",
    colorCategory: "Black",
    configuration: "Фаркоп",
    location: "Хоргос",
    exwPrice: "$43 800",
    notes: "",
    battery: "",
    wheels: "",
    packages: "",
    image: "/images/cars/lynk-and-co-900-20t-ultra-2025-black.jpg",
    category: "lynkco-900",
  },
  {
    id: "lynkco-900-lynk-co-900-20t-ultra-2025-14",
    brand: "Lynk & Co",
    model: "900 2.0T Ultra, 2025",
    fullModel: "Lynk & Co 900 2.0T Ultra, 2025",
    year: 2025,
    price: "366 900",
    exteriorColor: "Черный",
    interiorColor: "Бежевый",
    colorCategory: "Black",
    configuration: "Фаркоп",
    location: "Хоргос",
    exwPrice: "$43 800",
    notes: "",
    battery: "",
    wheels: "",
    packages: "",
    image: "/images/cars/lynk-and-co-900-20t-ultra-2025-black.jpg",
    category: "lynkco-900",
  },
  {
    id: "lynkco-900-lynk-co-900-20t-ultra-2025-15",
    brand: "Lynk & Co",
    model: "900 2.0T Ultra, 2025",
    fullModel: "Lynk & Co 900 2.0T Ultra, 2025",
    year: 2025,
    price: "366 900",
    exteriorColor: "Серебристый",
    interiorColor: "Бежевый",
    colorCategory: "Gray",
    configuration: "Фаркоп",
    location: "Хоргос",
    exwPrice: "$43 800",
    notes: "",
    battery: "",
    wheels: "",
    packages: "",
    image: "/images/cars/lynk-and-co-900-20t-ultra-2025-gray.jpg",
    category: "lynkco-900",
  },
  {
    id: "lynkco-900-lynk-co-900-20t-ultra-2025-16",
    brand: "Lynk & Co",
    model: "900 2.0T Ultra, 2025",
    fullModel: "Lynk & Co 900 2.0T Ultra, 2025",
    year: 2025,
    price: "366 900",
    exteriorColor: "Серебристый",
    interiorColor: "Оранжевый",
    colorCategory: "Gray",
    configuration: "Фаркоп",
    location: "Хоргос",
    exwPrice: "$43 800",
    notes: "",
    battery: "",
    wheels: "",
    packages: "",
    image: "/images/cars/lynk-and-co-900-20t-ultra-2025-gray.jpg",
    category: "lynkco-900",
  },
  {
    id: "lynkco-900-lynk-co-900-20t-ultra-2025-17",
    brand: "Lynk & Co",
    model: "900 2.0T Ultra, 2025",
    fullModel: "Lynk & Co 900 2.0T Ultra, 2025",
    year: 2025,
    price: "366 900",
    exteriorColor: "Серебристый",
    interiorColor: "Синий",
    colorCategory: "Gray",
    configuration: "Фаркоп",
    location: "Хоргос",
    exwPrice: "$43 800",
    notes: "",
    battery: "",
    wheels: "",
    packages: "",
    image: "/images/cars/lynk-and-co-900-20t-ultra-2025-gray.jpg",
    category: "lynkco-900",
  },
  {
    id: "lynkco-900-lynk-co-900-20t-ultra-2025-18",
    brand: "Lynk & Co",
    model: "900 2.0T Ultra, 2025",
    fullModel: "Lynk & Co 900 2.0T Ultra, 2025",
    year: 2025,
    price: "366 900",
    exteriorColor: "Синий",
    interiorColor: "Оранжевый",
    colorCategory: "Blue",
    configuration: "Фаркоп",
    location: "Хоргос",
    exwPrice: "$43 800",
    notes: "",
    battery: "",
    wheels: "",
    packages: "",
    image: "/images/cars/lynk-and-co-900-20t-ultra-2025-blue.jpg",
    category: "lynkco-900",
  },
  {
    id: "lynkco-900-lynk-co-900-20t-ultra-2025-19",
    brand: "Lynk & Co",
    model: "900 2.0T Ultra, 2025",
    fullModel: "Lynk & Co 900 2.0T Ultra, 2025",
    year: 2025,
    price: "366 900",
    exteriorColor: "Синий",
    interiorColor: "Синий",
    colorCategory: "Blue",
    configuration: "Фаркоп",
    location: "Хоргос",
    exwPrice: "$43 800",
    notes: "",
    battery: "",
    wheels: "",
    packages: "",
    image: "/images/cars/lynk-and-co-900-20t-ultra-2025-blue.jpg",
    category: "lynkco-900",
  },
  {
    id: "lynkco-900-lynk-co-900-20t-ultra-2025-20",
    brand: "Lynk & Co",
    model: "900 2.0T Ultra, 2025",
    fullModel: "Lynk & Co 900 2.0T Ultra, 2025",
    year: 2025,
    price: "366 900",
    exteriorColor: "Синий",
    interiorColor: "Бежевый",
    colorCategory: "Blue",
    configuration: "Фаркоп",
    location: "Хоргос",
    exwPrice: "$43 800",
    notes: "",
    battery: "",
    wheels: "",
    packages: "",
    image: "/images/cars/lynk-and-co-900-20t-ultra-2025-blue.jpg",
    category: "lynkco-900",
  },
  {
    id: "lynkco-900-lynk-co-900-20t-ultra-2025-21",
    brand: "Lynk & Co",
    model: "900 2.0T Ultra, 2025",
    fullModel: "Lynk & Co 900 2.0T Ultra, 2025",
    year: 2025,
    price: "366 900",
    exteriorColor: "Белый",
    interiorColor: "Оранжевый",
    colorCategory: "White",
    configuration: "Фаркоп",
    location: "Хоргос",
    exwPrice: "$43 800",
    notes: "",
    battery: "",
    wheels: "",
    packages: "",
    image: "/images/cars/lynk-and-co-900-20t-ultra-2025-white.jpg",
    category: "lynkco-900",
  },
  {
    id: "lynkco-900-lynk-co-900-20t-ultra-2025-22",
    brand: "Lynk & Co",
    model: "900 2.0T Ultra, 2025",
    fullModel: "Lynk & Co 900 2.0T Ultra, 2025",
    year: 2025,
    price: "366 900",
    exteriorColor: "Белый",
    interiorColor: "Синий",
    colorCategory: "White",
    configuration: "Фаркоп",
    location: "Хоргос",
    exwPrice: "$43 800",
    notes: "",
    battery: "",
    wheels: "",
    packages: "",
    image: "/images/cars/lynk-and-co-900-20t-ultra-2025-white.jpg",
    category: "lynkco-900",
  },
  {
    id: "lynkco-900-lynk-co-900-20t-ultra-2025-23",
    brand: "Lynk & Co",
    model: "900 2.0T Ultra, 2025",
    fullModel: "Lynk & Co 900 2.0T Ultra, 2025",
    year: 2025,
    price: "366 900",
    exteriorColor: "Белый",
    interiorColor: "Бежевый",
    colorCategory: "White",
    configuration: "Фаркоп",
    location: "Хоргос",
    exwPrice: "$43 800",
    notes: "",
    battery: "",
    wheels: "",
    packages: "",
    image: "/images/cars/lynk-and-co-900-20t-ultra-2025-white.jpg",
    category: "lynkco-900",
  },
  {
    id: "lynkco-900-lynk-co-900-20t-ultra-2025-24",
    brand: "Lynk & Co",
    model: "900 2.0T Ultra, 2025",
    fullModel: "Lynk & Co 900 2.0T Ultra, 2025",
    year: 2025,
    price: "366 900",
    exteriorColor: "Серый",
    interiorColor: "Оранжевый",
    colorCategory: "Gray",
    configuration: "Фаркоп",
    location: "Хоргос",
    exwPrice: "$43 800",
    notes: "",
    battery: "",
    wheels: "",
    packages: "",
    image: "/images/cars/lynk-and-co-900-20t-ultra-2025-gray.jpg",
    category: "lynkco-900",
  },
  {
    id: "lynkco-900-lynk-co-900-20t-ultra-2025-25",
    brand: "Lynk & Co",
    model: "900 2.0T Ultra, 2025",
    fullModel: "Lynk & Co 900 2.0T Ultra, 2025",
    year: 2025,
    price: "366 900",
    exteriorColor: "Серый",
    interiorColor: "Синий",
    colorCategory: "Gray",
    configuration: "Фаркоп",
    location: "Хоргос",
    exwPrice: "$43 800",
    notes: "",
    battery: "",
    wheels: "",
    packages: "",
    image: "/images/cars/lynk-and-co-900-20t-ultra-2025-gray.jpg",
    category: "lynkco-900",
  },
  {
    id: "lynkco-900-lynk-co-900-20t-ultra-2025-26",
    brand: "Lynk & Co",
    model: "900 2.0T Ultra, 2025",
    fullModel: "Lynk & Co 900 2.0T Ultra, 2025",
    year: 2025,
    price: "366 900",
    exteriorColor: "Серый",
    interiorColor: "Бежевый",
    colorCategory: "Gray",
    configuration: "Фаркоп",
    location: "Хоргос",
    exwPrice: "$43 800",
    notes: "",
    battery: "",
    wheels: "",
    packages: "",
    image: "/images/cars/lynk-and-co-900-20t-ultra-2025-gray.jpg",
    category: "lynkco-900",
  },
  {
    id: "lynkco-900-lynk-co-900-20t-ultra-2025-27",
    brand: "Lynk & Co",
    model: "900 2.0T Ultra, 2025",
    fullModel: "Lynk & Co 900 2.0T Ultra, 2025",
    year: 2025,
    price: "366 900",
    exteriorColor: "Серебристый",
    interiorColor: "Оранжевый",
    colorCategory: "Gray",
    configuration: "Фаркоп",
    location: "Иу",
    exwPrice: "$42 900",
    notes: "",
    battery: "",
    wheels: "",
    packages: "",
    image: "/images/cars/lynk-and-co-900-20t-ultra-2025-gray.jpg",
    category: "lynkco-900",
  },
  {
    id: "lynkco-900-lynk-co-900-20t-ultra-2025-28",
    brand: "Lynk & Co",
    model: "900 2.0T Ultra, 2025",
    fullModel: "Lynk & Co 900 2.0T Ultra, 2025",
    year: 2025,
    price: "366 900",
    exteriorColor: "Белый",
    interiorColor: "Бежевый",
    colorCategory: "White",
    configuration: "Фаркоп",
    location: "Иу",
    exwPrice: "$42 900",
    notes: "",
    battery: "",
    wheels: "",
    packages: "",
    image: "/images/cars/lynk-and-co-900-20t-ultra-2025-white.jpg",
    category: "lynkco-900",
  },
  {
    id: "lynkco-900-lynk-co-900-20t-ultra-2025-29",
    brand: "Lynk & Co",
    model: "900 2.0T Ultra, 2025",
    fullModel: "Lynk & Co 900 2.0T Ultra, 2025",
    year: 2025,
    price: "366 900",
    exteriorColor: "Белый",
    interiorColor: "Синий",
    colorCategory: "White",
    configuration: "Фаркоп",
    location: "Иу",
    exwPrice: "$42 900",
    notes: "",
    battery: "",
    wheels: "",
    packages: "",
    image: "/images/cars/lynk-and-co-900-20t-ultra-2025-white.jpg",
    category: "lynkco-900",
  },
  {
    id: "lynkco-900-lynk-co-900-20t-ultra-2025-30",
    brand: "Lynk & Co",
    model: "900 2.0T Ultra, 2025",
    fullModel: "Lynk & Co 900 2.0T Ultra, 2025",
    year: 2025,
    price: "366 900",
    exteriorColor: "Белый",
    interiorColor: "Оранжевый",
    colorCategory: "White",
    configuration: "Фаркоп",
    location: "Иу",
    exwPrice: "$42 900",
    notes: "",
    battery: "",
    wheels: "",
    packages: "",
    image: "/images/cars/lynk-and-co-900-20t-ultra-2025-white.jpg",
    category: "lynkco-900",
  },
  {
    id: "lynkco-900-lynk-co-900-20t-ultra-2025-31",
    brand: "Lynk & Co",
    model: "900 2.0T Ultra, 2025",
    fullModel: "Lynk & Co 900 2.0T Ultra, 2025",
    year: 2025,
    price: "366 900",
    exteriorColor: "Серый",
    interiorColor: "Синий",
    colorCategory: "Gray",
    configuration: "Фаркоп",
    location: "Иу",
    exwPrice: "$42 900",
    notes: "",
    battery: "",
    wheels: "",
    packages: "",
    image: "/images/cars/lynk-and-co-900-20t-ultra-2025-gray.jpg",
    category: "lynkco-900",
  },
  {
    id: "lynkco-900-lynk-co-900-20t-ultra-2025-32",
    brand: "Lynk & Co",
    model: "900 2.0T Ultra, 2025",
    fullModel: "Lynk & Co 900 2.0T Ultra, 2025",
    year: 2025,
    price: "366 900",
    exteriorColor: "Серый",
    interiorColor: "Бежевый",
    colorCategory: "Gray",
    configuration: "Фаркоп",
    location: "Иу",
    exwPrice: "$42 900",
    notes: "",
    battery: "",
    wheels: "",
    packages: "",
    image: "/images/cars/lynk-and-co-900-20t-ultra-2025-gray.jpg",
    category: "lynkco-900",
  },
];
